### ISSUE TITLE
Change toFloatChannelData() namespace to resolve conflict with AudioKit Swift Package

### ISSUE THREAD

**Issue by NickCulbertson** [AudioKit/Waveform#5]
### Description

toFloatChannelData is in both Waveform & AudioKit packages. Changing the name in Waveform would make life easier when using them together in the same project.

### Proposed Solution

Changing the name from toFloatChannelData() to toFloatChannelDataWaveform().

### Describe Alternatives You've Considered

NA

### Additional Context

This is low priority. I'll get to it when I have time.

**Comment by aure** [comment]
Wasn't this resolved here? https://github.com/AudioKit/Waveform/pull/4

**Comment by NickCulbertson** [comment]
Oh yes, my mistake! I was on an earlier version of Waveform.
